#syntax=docker/dockerfile:1.2

FROM alpine:3.12

ARG docker_id
RUN    apk update \
    && apk add          \
        bash            \
        docker          \
        docker-compose  \
        shadow          \
    && groupmod -g ${docker_id} docker